name: docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:

      # Check out source
      - uses: actions/checkout@v2

      # Build documentation
      - name: Building documentation
        run: |
          apt-get update
          apt-get -y install libgl1-mesa-glx
          pip install -e .[dev]
          sphinx-build docs/ docs/_build -b dirhtml

      # Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
